apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: docker-registry-secret
  namespace: dalai
spec:
  encryptedData:
    .dockerconfigjson: AgAYc6OjNb+znLrsETyDyvKfI19uQGd9eJJv0MohS7+weyl9NtPk/fM2AgYLDzMsafG4u0vFmIIwdtPhvJiUPF5sY8g5X14eIeAu74S/wntuwLBjEDMGlCZWZ3+UgZOkcb55sF9SDBaXxmZzabJiop9oUWl+I57oeZAUqq3e0zxMg1d7bjckXoxW8znBTmm3r2f7TvCOmlA3oAxL9bL4QPEpzV3pnYnI4w+0XdQDLyutGwWkAjxT8G7ko7l7CxKOMWw8DDkGIGAJNlD+wZAb0V5Xk/xWw1bZxsjQa3rwhSv8aUoUSof/MwqvPSo8tLk2ymujwRQkqYrjYBN9or0ntnvFCL+5WOT/iBOsT3lO6ddXPJrTgFwm7TDT6lvG8yFg2GPNhgOOzEFBX5BdGTzBsY+G8r7qNDG5424SYGjMioUaV8PdLu4pIGsM71Qin/STC1EzvYzTzopYc4KX71EZlL7VjWRtO5wn8/gVGveZOtkrdxNDW6oDIlsxm9LB8Y1WBoOm+AowCDW3RjbYpRxBxF0KGpC7wyx0Gb+GLOf7CE7rSz7mwbHlk9rqoWRflszWPhK6YHik91Xg7BPZ9/e3poK7kAuZC9LMinLjd+Z5McI3Xd3IITkI/Ema7n/m7WtTBIQq9LsgOLtva1incnb38Y1qhXAnSEz/u8XbL4rzcJsjUNg6lnVq3YfOhkOWm20QawNnui0aLJygLUDNRBeCJtqTiLJK1/4gTnfSX/GCtcr8H0SqhU517+2rpYdpWf1z/T6GUBKUQtoWh+pdqrv14SRRDkhZ7Kl31L5FuIaltxxk3Zuk8j1r7+s1k7EiXn1zwB5fPKdBypdFO0f9T89SJkcAQa/51VX19c9ipNGrHn8xJhW7TVWrIMibwcxVWl0oISskIYmZgQdz+JA6nK56CSZVW/rRw3+kVLg0SqxF531cOnWVl0MeKUzLWXn0qqje+3IgqdNR9uQ=
  template:
    metadata:
      creationTimestamp: null
      name: docker-registry-secret
      namespace: dalai
    type: kubernetes.io/dockerconfigjson

