apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-secret
  namespace: dalai
spec:
  encryptedData:
    accessKey: AgDB7X5cnNpDro3C+ZAfDr+7zygxZ/LeBtW7CmvURmCcxwxMIlhUr5+ned4z8jUVzgUOouIPAPDL42Lo8rsthZHQ/0uLqAF9BCvIVAFr+6/NiohRCtqj9FGq67eZY1B9K+zVKbIEDool8kGUiscKCOJ2QZ+EWz2yAf1Hl6+/e4zoEIr8q1lC05P1nUML7VEWDcZrPVvRH9ZgcdhMQh9je0ZqCdaY3yREa8RxtxueLAlbFV6Qr/0lmZAHjJtzwPD5zcPJx0ftAU2UxnQDkLSAtVKo95/qC7zRFrdojZ/+0Czpf2dsy1eNc3U0dLK5sC3vqB1HtYtQlpuu2TnLOKNeIY8xK18WlKnZbC/MUAUuitJDQgXmuQXLfokiLlPYKY3HchwyW/1K0wbYPb6wwLo9+qUYd+CO6C5vxmRelD0YCixYy3CETznkuI4enIr6I3lHs0GaD3zKjr9xj3XemzqlVQbmHqkiMDgBnuU1y2+woFZNY97dSNFSNJdtB4ErXN1nHZNbCmn3kMcER6UtaB5wUkOrGwTH0xMpRunPnC8FiGSA5hn0hqXUHjn32s9gm5R8D4Hxl8FvOqUVrboLYr7iZGbN10zjc9uiWOEMKTNhLA9HPIepKaYxKP2tq/M+3iMRBn72g9exZp37E+7o0eYtSfD5D1j7X03zOAiyw3W7OZOVPf3LJ0M1VjGHIEvKzNGQhhmJqTC2
    accessSecret: AgAwweSpgSz19XnZfpVZFLGoUYXdhq+vkyNEWJuj7CYOeCRbzT00FU0qZNURnOFdz8lVgYvTsJ8JJLkEsQUPUGv2YWbm9C5lhoL09eGbxKhxbwV99cDGcryi9/HWbxpeFlKN6uBptYH2l2CSFPnYB/DDDASQ72UaeAjZhv57mqh4t6ClEuAEHmBjIhbh32GXQyYsY9ED+U0j3wATkRL4FFOb5Kpt60OMGhYR1y3IPeWyyq4wGS1Q5Do0O1mAzi57UPqZuzPkgn8sjCbFUFRjcgUMZKERZ/5JsI80ui8P6dnQHT3O1Ge+kvc+yWbMXMHdR6oWpXdOTRoG8fWmBGcfoM7GLsH+YNG7KwLdLk85UnAQrR9db+QFPRWcW8+H/jxGg3QxWB0XlaTwHyUvZEyX5ihNR7kjPmWnlH3n1t+HXlfWgZLRXsWS6/6RX8v3u3WgUtWg2NN4bZvj+486Lm1Ed4gmUeUkQbUXHE5m8Fnai9LndxNf16U5NvnumosVQaf7xf7ZIvIG9JEcq8xg7aupeCQIY+LP+9Giszjrgux8qxScbQDHdH3e0FpHmdzpVIPcGaEyeCxhBj2nYLw4Ul82dTPGYFFT+qdiwP/rv0+pGkCQrjFI1HrNAYWVxq4had2A5ubQx3cSa+u7LyfB+YuUS49YVIup44zk+nLJo0TCbtmbC+kA+nBrv87sgRPkm1T08uXiVUXZkidOVBTHUr57mSumoy49wg==
  template:
    metadata:
      creationTimestamp: null
      name: minio-secret
      namespace: dalai
    type: Opaque

