apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dalai-alpaca
  namespace: dalai
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dalai-llama
  namespace: dalai
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi