apiVersion: v1
kind: Service
metadata:
  name: synology
  namespace: default
spec:
  type: ExternalName
  externalName: 192.168.1.237 
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: synology
  namespace: default
spec:
  rules:
  - host: synology.homelab.bartbrinkman.nl
    http:
      paths:
      - backend:
          service:
            name: synology
            port:
              number: 5000
        path: /
        pathType: ImplementationSpecific