apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: dalai
spec:
  entrypoint: dalai   
  templates:
    - name: dalai
      steps:
        - - name: build
            template: build

    - name: build
      inputs:
        artifacts:
          - name: dalai-source
            path: /src
            git:
              repo: https://github.com/cocktailpeanut/dalai.git
              revision: "main"
      container:
        name: build
        image: docker
        env:
          - name: DOCKER_HOST
            value: tcp://localhost:2375
          - name: REGISTRY_USERNAME
            valueFrom:
              secretKeyRef:
                name: docker-registry     
                key: username     
          - name: REGISTRY_PASSWORD
            valueFrom:
              secretKeyRef:
                name: docker-registry     
                key: password
        workingDir: /src
        command:
          - sh
        args:
          - "-c"
          - |
            until docker ps; do sleep 3; done; 
            docker login -u $REGISTRY_USERNAME -p $REGISTRY_PASSWORD minio-docker-registry.minio.svc.cluster.local:5000 && 
            docker build . -t minio-docker-registry.minio.svc.cluster.local:5000/dalai:latest && 
            docker push minio-docker-registry.minio.svc.cluster.local:5000/dalai:latest
      sidecars:
        - name: dind
          image: docker:dind
          command: ["dockerd", "--host", "tcp://127.0.0.1:2375", "--insecure-registry", "minio-docker-registry.minio.svc.cluster.local:5000"]
          args:
            - "--mtu=1450"
          env:
            - name: DOCKER_TLS_CERTDIR
              value: ""
          securityContext:
            privileged: true
          mirrorVolumeMounts: true
        
            
