apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: dalai
spec:
  entrypoint: dalai   
  volumeClaimTemplates:   
    - metadata:
        name: workdir                     
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi

  templates:
    - name: dalai
      steps:
        - name: clone
          template: clone

    - name: clone
      inputs:
        artifacts:
          - name: dalai-source
            path: /src
            git:
              repo: https://github.com/cocktailpeanut/dalai.git
              revision: "main"
      container:
        image: debian
        command: [sh, -c]
        args: ["ls -l /src"]
        volumeMounts:                     
          - name: workdir
            mountPath: /src