apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: dalai
spec:
  entrypoint: dalai   
  volumeClaimTemplates:   
    - metadata:
        name: workdir                     
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi

  templates:
    - name: dalai
      steps:
        - - name: build
            template: build

    - name: build
      inputs:
        artifacts:
          - name: dalai-source
            path: /src
            git:
              repo: https://github.com/cocktailpeanut/dalai.git
              revision: "main"
      container:
        name: build
        image: docker
        env:
          - name: DOCKER_HOST
            value: 127.0.0.1
        command:
          - sh
        args:
          - "-c"
          - |
            docker build .
      sidecars:
        - name: dind
          image: docker:dind
          # command: [dockerd-entrypoint.sh]#
          command: ["dockerd", "--host", "tcp://127.0.0.1:2375"]
          env:
            - name: DOCKER_TLS_CERTDIR
              value: ""
          securityContext:
            privileged: true
          mirrorVolumeMounts: true
