heimdall:
  ingress: 
    main: 
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
      hosts:
      - host: heimdall.homelab.bartbrinkman.nl
        paths:
        - path: /
      tls:
      - secretName: heimdall-tls
        hosts:
        - heimdall.homelab.bartbrinkman.nl
        
  persistence:
    config:
      enabled: true
      type: pvc
      accessMode: ReadWriteOnce
      size: 1Gi