apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: portainer-scaledobject
  namespace: portainer
spec:
  idleReplicaCount: 0
  minReplicaCount: 1
  maxReplicaCount: 1
  pollingInterval: 5
  cooldownPeriod: 300
  scaleTargetRef:
    name: portainer
  triggers:
  - type: prometheus
    metadata:
      serverAddress: http://kube-prometheus-stack-prometheus.monitoring:9090
      metricName: nginx_ingress_controller_requests
      threshold: '0.5'
      query: group(rate(nginx_ingress_controller_requests{exported_namespace="portainer"}[2m]) > 0)