apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysql
  namespace: mysql
spec:
  encryptedData:
    mysql-password: AgDHnqMlHogjlZDJkHggpQZYpBBaC8cGyOuRhMMTYWUnFf7lknyBwGedESNe23hk9xOro7abTFZxD7e6KIFZ8Y/AKV+cW7HGamdrwKiRD5K/rssMmPDG10bzcjvBPaJ3cH28VkUXBHzlzI6FoMPml14dTMj1Qx4v8M1Gb/tUA545Ibgcg+Qd0ifF05hH2RRlzDOFdwYGpOnH/Y0VjDKuwwEPw0ioZCDmctg9iqK1kSP6CDoREQ1b5x65DfQsFKA6sf0nHCAdanC9RpjbGGqBtsW3eMXhYawgSzcNi11NvEZpaZfXzieoKzUJsZlRwqakndxkwBWQE5JUk7ptzNl0o7r/Rl3MH4jpC0wN+YzGBRoOHIjyZmiJ8k3KsEMlcspygTaeeHCIP4j7quj1l3ran+G22wCJ2nqYfNoeJFYwKxrerZzeJIEJKBVcpwMdXyoOYBr+Yu4t/OhBCLpOUoSyZe17Xm76AZhE7/HPEll2q0T0poNrsBPRblXoDunfRT7qtGep34eWwE69EFQwjxzj9AS5AmD8xvdUnHHm1OWYoFFNrFtfDYhYGLmIwgdEgpjhT0OAsXiRpD3mEcoVVPx1mAoZ234ajBx6MfJHH6yFo8ciWwG1IPp5J3zceqv1QUmd4BNSV3nM5dWaMQxtphvrjiG+dZNoHg512uZDQ4Ltsx7smKSvHtkDOquu/Eh2m0ELdA823PNKVeicc+LFtpP5KUbL
    mysql-root-password: AgCzariONdDNs945ssikx730AB2NEGYAB+0lWK/UWcN2cb6dpiktgPyWhwlSqHTEGoZbytCAozbGJ468z0dEEHmElCOtDgF/hIwG6hKxBmDRVcxAOFC/39bLHDFy9vyel8OZxCwE+Sf4RHjxWRheOqJuYmc5+qbAFYcEX6GmRTdtb1Irzy8dQR3RGrPk9heXYsmB/AmhIBl/nfofFKtdDb/FeWu+Y5zX4YOwAQQAA1eOiSA2jaoLH4YCw8P7sNDXrSkjO9u8IJoUUPVwlOFQ+JZyLc7qjOY6n5JbIhFwrk0Dz9WAqd9gcmSkdGKDjv/9CQuhEN5lp2x/v3wBjc557kiO9nTObyDEsXgAK20GvzNBkiSPTw1XHCSEEdBumHRqDHFNG+eoVZXPqSrRRZ/z/jLrgThxhRnwpmJGSwqWhOPHZoY4eg39pQv+PJr52uAZl11V1UPYJnaGCCEkdK1othyeKFeAFZaWJQBzYKa1a6UcizVEYLKte53UY5g1A5Xpvfhc27klymlGDGbMLBSq2+aS3xrFPNDIdY8Cw6WVc7absFqF9QRnmO4YhpUTynNZMmMLP+f10sMwnr35FXL/Km+bugSwlnf4jdfYCQY+6Qj+d5Hwumssa4+NkMfLb3l56jwG3hbSkGnIyNp2wxcyNpOjZ+ZpVygIXL4zAwtzDQe/HH7AlJu+rYuG1cKhUoZZN8BdlL7LkyQNXpEGyngYqriQ
  template:
    metadata:
      creationTimestamp: null
      name: mysql
      namespace: mysql
    type: Opaque

