apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-payment
  labels:
    app: simple-payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-payment
  template:
    metadata:
      labels:
        app: simple-payment
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80