apiVersion: v1
kind: Service
metadata:
  name: bootnode
  namespace: ethereum
  labels:
    app.kubernetes.io/name: bootnode
spec:
  selector:
    app.kubernetes.io/name: bootnode
  clusterIP: None
  ports:
    - name: discovery-udp
      port: 30301
      protocol: UDP
    - name: discovery-tcp
      port: 30301
      protocol: TCP
    - name: http
      port: 8080