apiVersion: v1
kind: ConfigMap
metadata:
  name: geth-miner
  namespace: ethereum
  labels:
    app.kubernetes.io/name: geth-miner
data:
  genesis.json: |
    {{- range .Files.Lines "genesis.json" }}
    {{ . }}{{ end }}