apiVersion: v1
kind: ConfigMap
metadata:
  name: geth
  namespace: ethereum
  labels:
    app.kubernetes.io/name: geth
data:
  genesis.json: |
    {
      "config": {
        "chainId": {{ int .Values.chainId }},
        "homesteadBlock": 0,
        "eip150Block": 0,
        "eip155Block": 0,
        "eip158Block": 0
      },
      "difficulty": "0x400",
      "gasLimit": "2000000",
      "nonce": "0x0000000000000000",
      "alloc": {}
    }