apiVersion: v1
kind: Secret
metadata:
  name: geth-miner
  namespace: geth-miner
  annotations:
    "helm.sh/hook": "pre-install"
  labels:
    app.kubernetes.io/name: geth-miner
type: Opaque
data:
  password: "{{ randAlphaNum 24 | b64enc }}"