apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: argo-server-sso
  namespace: argo
spec:
  encryptedData:
    client-id: AgCMohMQ04UpUKTt98oKOSB2KwJX+EF6c7ltKJICborBki0Zc5xKUnFzTKI1HVLqbTPoAHFjR4U+GXWR8sgkbq8zBXejBpHfq4a6hHIr7I8jSfr7pwvIC6ba+fZNHPE6aCfo+EJmAVdPyEL0PKHgWdFEuJOxpJOVFHo75vZ1yTDXPrfgIfZrvfAtX7W4EOwU7BNj8gURLZRqCMy/88MRiilfYKlLZCRCYbVnL9v2KdAwZKiDdYCRq8EspBSgV63IuURhbuiQEIDQxtgnSc0M+PRYRN2HsYts6gXjYPgILSW3RaSUsSzKdPgE6kgpxkSlVTKtCJNxYOn+ukapuZoJY7VLm3Zg3lV8AtFzkf/5m31PUijjfaNbwUI3t5ooBQyzGOmroklZWgxhWZhSaAV7cKHjhbNPafZ1hdHyKTQiXAXyGPtvfjk9iNB5m1qz13O+a7xhpa8Aj5aUDlzH45GdwiPhnBwMCm4H1HTLiwbUYp7iv6lm956QkM/sNtIxTn7d98NZE8Mq+zRx+egw37y9lyCTcc3nsgNqIGQKkhTCo1IvkTfWdzVCfrx880/CNdso7E+eUfFsSqhge1IfOv9UgDJfSGhD20k3e48lu/rV5F6BihRh2DuUjHIwDkDh4a1jdzJKUv8b6Yzr9mb415FTRfWNoaPL8HE8kRBrDK/X1Bz2dw7Q8NBg+uBeF0tph9cU0b0M0+O5FUddeGAtXQG00Ef0FNhxTg==
    client-secret: AgCr8zUyu/nrQTmOVqWTyxxeg/iFU/tJLmeYcxxs1vKzox188x+EEJoN/EjzfEV9qQ+5tbTf7hzCBQnbgwmJAVk6QsoOWy3i6wT4UG+mNHD7yfOZNj3o1RPXdMrwzuwrLhircQPHG6AY75xOKyw6dVrdgAfQfHlI3KZ+6hSs4g8Rr1hEf5qptuXGMf3IhNUbtlqroR+L0zk+Xl7riT8wjFrNrVQePmZ5QmRONkS4HokZsfBWSNX63pqTK3p9eiaoskqRHPDC5IGUfB7xgHx+a9GiavOSXcg7E+dHFNy2riqwNTJ3RrmAEmkcL7uH4kNsTcdB19iiOiruKw2fABAkrIG3O7bGudsmR7sQXHpo1kMJ1MDTqVOIAlisBiTAa80XnTzzLbCUV8mbNjqEciw1hOgaDfWUaF0CtavG/L9/ZK2Hh6vmVifewwtwl1y+pvSZla0kh5RTRLlaM1ytAYeSKv1sEgER6oJvt7R/zbG/BGxCmN7cJBHHBlRxHRSZae+tKkp7GeTzeh1Xac/C3ube/zxC/pwLNWTm5Ls25Lv4guwEIusjhlSJZKA9crYlv6YnY8TvdKZW1egPjZZCoAJRBNhRawuKejjCJifi7EMbWu/V1DstyNypL6SwhBbCEpIsnx7bQjYKzPfr4FADjhllM3qf8MNKqma2anIiluCHhYmPHw+JC7oF4gwqXeeHvWcirwZiMkVWGnj7kOkm4VVxEVwpp1exDbm8WOqS8pTGf1HXuCoJ+46UAREB
  template:
    metadata:
      creationTimestamp: null
      name: argo-server-sso
      namespace: argo
    type: Opaque

