apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
spec:
  auth:
    strategy: anonymous
  deployment:
    accessible_namespaces: ["**"]
  external_services:
    prometheus:
      url: http://kube-prometheus-stack-prometheus.monitoring:9090
  istio_component_namespaces:
    prometheus: monitoring