apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: bart.brinkman@gmail.com
    privateKeySecretRef:
      name: letsencrypt
    solvers:
    - http01:
        ingress:
          class: ingress-nginx
          ingressTemplate:
            metadata:
              annotations:
                kubernetes.io/ingress.class: ingress-nginx
                ingress.kubernetes.io/ssl-redirect: "false"
                nginx.org/redirect-to-https: "false"