sealed-secrets-web:
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
    hosts:
      - host: kubeseal.homelab.bartbrinkman.nl
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: kubeseal-tls
        hosts:
          - kubeseal.homelab.bartbrinkman.nl