apiVersion: v1
kind: ConfigMap
metadata:
  name: server-config
data:
  map-gen-settings.json: |
    {{- range .Files.Lines "config/map-gen-settings.json" }}
    {{ . }}{{ end }}
  map-settings.json: |
    {{- range .Files.Lines "config/map-settings.json" }}
    {{ . }}{{ end }}
  server-settings.json: |
    {{- range .Files.Lines "config/server-settings.json" }}
    {{ . }}{{ end }}
    