grocy:

  image: 
    tag: '3.3.1'

  ingress: 
    main: 
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
      hosts:
      - host: grocy.homelab.bartbrinkman.nl
        paths:
        - path: /
      tls:
      - secretName: grocy-tls
        hosts:
        - grocy.homelab.bartbrinkman.nl
        
  persistence:
    config:
      enabled: true
      type: pvc
      accessMode: ReadWriteOnce
      size: 1Gi