apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: peppermint
  namespace: inventory
spec:
  encryptedData:
    password: AgCFemrZarEjLHVvtBBP2WaGjsDE5C2qw8H0/k5z1S/BA78OSEZM0rnB/IHpya50qEleDeNTFkf5EJLzU/JBGTRbWEAOiHd8d+3tsBzLVDT6rROZ9G30Toe1P+3RQ/ZhetRC9nebrN8XDQeiS68NUzhZldysKK08FV6g5jgWvdVpx1a0brfKdHt9rV+2jIIEg4N3jgZF5IDOOC20tsxhd+Dg5x3fQZDV4zYqCFUNiVJ3S/uv9EjQzTp6xxe5IaJ2Cgs8bCBr000YhTP0b1M7FFa0ZPQIV48/BNHWnRSmrPz1p1uuY5PmGsKdohvBB/Hx0cWw+bVQTIAcgljMCSnlnfbil4CdbJ146Ww8yaNAl9m4WOG2VtiZf2FUw3IjavpBHbSg9AGlL557CaZKXLSeyHltVdJXorURiAHJ+DwE372xMsizkaEfVfkvjnLHhHSRdpeo9lUXNfiZfgwLJLEMR1dtDnPmH2+Y7KjddCKJfMocIIllDGFEorliRyxSbVLmpT8Waqu3iUxsowbeSzuF0E2XwyvnpA9ZN4eveDyZnrnPnBDZAs1FiJpBPFIg3BqAlKRDbojmXphDrAb68Q5QkgJweaIFFauTtqxfJe+hTE6WM2Z+1FNXO+2daqtfYZDHPsEY075fKcd3JVzsl6aodOrGjpjiXUKgyILz+wpa95h1lmyC9GLeqoNGO2+zJPDxOEWiFQVC2vWCvPnCnOliR9eBwxwW1Q==
  template:
    metadata:
      creationTimestamp: null
      name: peppermint
      namespace: inventory
    type: Opaque
