apiVersion: v1
kind: Secret
metadata:
  name: silverstrike
  namespace: finance
type: Opaque
data:
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace "silverstrike") | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  {{- $secretKey := (get $secretData "secret-key") | default (randAlphaNum 32 | b64enc) }}
  secret-key: {{ $secretKey | quote }}