apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: minio
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: minio
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
  ignoreDifferences:
    - kind: DaemonSet
      jsonPointers:
        - /status

