---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress
  labels:
    name: ingress
    annotations:
      argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
    annotations:
      argocd.argoproj.io/sync-wave: "-1"
