apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio
  namespace: minio
spec:
  encryptedData:
    rootPassword: AgCQCxg5jl3J4Emb7r6dLh+7Z7CfrWPfhrxqSAYbGI1QNOgl4UQtF/F2LJsSKRyRpmE9N7MBd+0UrYx1uuVh9hRttKWU146pk3uSdg/vbyzionTaaLGyp704OhWKGByfs3j1hOzO0k2g/I5jJfgYG4xBrvOBtsbT8PJNZDPw1PWrMMH+LzzIy+BbRSiB2Rpg6P2cFOLT5SXb3UML5+5TFy1UqouUkyfebHJp3yjx3MQIC3NsFJ0oTaCzSmvvgQb1WTjf8Xsfz5k5Fkz3MNSaZk93S29rXVPKqyVWIVVC5dK4b2XUVTL7a9TFlrJYWHRW3waarSlOVBzJ1IUBdd9WlFep5gqpki/uGyBCugAX336E6oFM5IGXTqb5M3mJNChYcmpLI+tKi0s3Lq1G9BzqV49YtCOqFsFiccQTDLwrYYGq9nDSvmpzOvWSZ6XM6Xy/cBTDHpxeMRoWjRw9kwPMhJPEkvW87g1c1HmIYCFcQ/+CrsiCn/+uTRlC6iyb1bbOrlM95f2ev7Cb5jQ56QyB5j2UOewv2atpmyw3vNZTAGaJ9hOyVn8DmaN5epbZQMOyktqDtKBmsbU/8PAxPOo69wQ4sRjqIDP6SqvN0oKkVJaOcleUNZMPJ48nOVVZX+sp8XIXwt4kI6TnpeLnaZJAf9n3MEiFlRD/E1bLEskQJItvw14FNFP2fT+hcJKpwVoW1J6YZk7C7cbGDwZdhsAD+W4Ae4R7Eg==
    rootUser: AgAMAZpCSwqsa2AsOZYU1dUKSBS0G9GUe8WF4tVV5tIUGneh+iRlyR80nu8RiryDkNMIAQ0INT2XiW9hzitG5hH/wCwOa3htp2px/wJdx/361hYaAA+cmCajHgErlLieS+eyXd+3HXY8kAyOBO/Pc6Rx5uA4kPgoNxSm55K8tOorMp2x0mzV0CoWzRDo05w0I78uMRgZB3sfxi6iME/x0N8e/gkSZvM9VL063AOoXl1A0MDF0/ebdO5m5iXsQ2MluFj7tHFMbP5ZXAjf9PAf3asfXIyiCkec7JPqaM4J8bf89GldhF/qeqHk5BPO7sO3ZdeO3O/ourtl4Jls+YuRkiGcBXAhvGwfZ/Ka8N2bn5lBbE7T4veJT5RWoMzqZxJzjTTQubKnEjlHh1Syjrgv39ZlWtUlsFnN0lHJ6ChHw3mjeQmBe+gZY5mO6En2Kqn2CN5Nu09dV2N+dTFgMumdtfJ2vEzvs3/L0Ftty23Yj9XEi9WE+QXxf21qHwBdzqwBTIOji5Cpca3OtsjMt9DaLoLjIk0az1FhAA5f1REhM86/IUUu/mILhwkLm42l/rhPapTkm6U+3BFJfIYDXJRhOF/IfpGcaqEsDpxr0F+0MwrBhvFBb3eOVsuJ1KI0MW/5I+cpg2cl7sX/TTFQCbVOrdSBgGIo9v1wCWQPZfCpp+QhVzjODAVoC4cxe3pYoYBZFa5fMSfJ
  template:
    metadata:
      creationTimestamp: null
      name: minio
      namespace: minio
    type: Opaque

