postgresql:
  global:
    postgresql:
      auth:
        username: postgres
        existingSecret: postgres
        secretKeys:
          adminPasswordKey: "adminPasswordKey"
          userPasswordKey: "userPasswordKey"
          replicationPasswordKey: "replicationPasswordKey"
  primary:
    initdb:
      scripts:
        peppermint.sql: |
          CREATE DATABASE peppermint;
          GRANT ALL PRIVILEGES ON DATABASE peppermint TO postgres;
